#!/usr/bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config focused_border_color     \#eee8d5
bspc config normal_border_color      \#586e75

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Downloads/solarized.jpg &
polybar main &
polybar bottom &
# setxkbmap -option grp:alt_shift_toggle es,us &
# ibus-daemon &
picom -b &
dunst &
mpd &

